services:
  whatsapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_SECRET=${INTERNAL_SECRET:-your-secret-here}
    volumes:
      - ./sessions:/app/.wwebjs_auth
    restart: unless-stopped